# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-09 13:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('desc', models.CharField(blank=True, max_length=255)),
                ('send_to', models.CharField(max_length=2048)),
                ('status', models.CharField(default='DRAFT', max_length=10)),
                ('deadline_date', models.DateField(default=datetime.date.today, verbose_name='Deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='DRAFT', max_length=10)),
                ('mapped_field_name', models.CharField(max_length=64)),
                ('field_name', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('desc', models.CharField(blank=True, max_length=255)),
                ('max_len', models.IntegerField()),
                ('manditory', models.BooleanField()),
                ('Request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.Requests')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.IntegerField(blank=True, null=True)),
                ('badRows', models.IntegerField(blank=True, null=True)),
                ('documentPath', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
                ('type', models.CharField(default='RESPONSE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.Requests')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, max_length=255)),
                ('max_len', models.IntegerField()),
                ('manditory', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.Requests')),
            ],
        ),
    ]
